//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTravel
{
    using System;
    using System.Collections.Generic;
    
    public partial class B2B_Locations
    {
        public int LocationID { get; set; }
        public string LocationName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string LocationType { get; set; }
        public string CityLocationID { get; set; }
        public string ProvinceLocationID { get; set; }
    }
}
